### ISSUE TITLE
Auto-Animate text is incorrect

### ISSUE THREAD

**Issue by cfjedimaster** [reveal/revealjs.com#24]
On the Auto-Animate page (https://revealjs.com/auto-animate/) there are two problems.

First, the second paragraph refers to the word "Magic" which isn't in the demo.

Secondly, I don't believe (but could be wrong) the demo code is correctly being used in the demo itself. So the demo code shows two H1s with text, "Auto" and "Animate", while the demo itself shows "Auto-Animate". Also, the changes in style don't seem to match the source code.

**Comment by hakimel** [comment]
Thanks Raymond! Those issues have been fixed and I took the opportunity to add another animation example as well.
