### ISSUE TITLE
Markdown page is misleading (incorrect?)

### ISSUE THREAD

**Issue by tmewett** [reveal/revealjs.com#26]
Hi, the page https://revealjs.com/markdown/ contains example code like this:

```html
<section data-markdown>
  <textarea data-template>
    ## Slide 1
    A paragraph with some text and a [link](http://hakim.se).
    ---
    ## Slide 2
    ---
    ## Slide 3
  </textarea>
</section>
```

implying it's possible to separate slides with `---`. However pasting this into the sample presentation leads to a single slide with horizontal rules on it.

I also notice that you don't need the inner textarea element - I don't know if this is supposed to work?

Thanks for your time

**Comment by rinaldi6109** [comment]
I noticed this, too. Example is not clear. I understood it after analyzing an example from another site. 
I ask to update the help page [https://revealjs.com/markdown/](https://revealjs.com/markdown/) replacing line 
`<section data-markdown>` to `<section data-markdown data-separator="---">` for the benefit of all new users.

**Comment by hakimel** [comment]
Thanks for bringing this up. There was a bug in reveal.js that prevented the default separator from working but this was recently fixed: https://github.com/hakimel/reveal.js/issues/2850

That said the example you highlighted above is correct and will work if used against reveal.js master. The fix will go out with the next version of reveal.js.
