### ISSUE TITLE
Offer to Help with Chinese Translation of Documentation

### ISSUE THREAD

**Issue by Edit-Mr** [reveal/revealjs.com#62]
Hi @hakimel ,

I'm a big fan of reveal.js and have been using it extensively for my presentations. I truly appreciate all the hard work and dedication that has gone into developing such an amazing tool.

As a native Chinese speaker and a passionate user of reveal.js, I would love to contribute to this project by helping with the Chinese translation of the documentation. I believe this will make the tool more accessible to Chinese-speaking users and help grow the community even further.

Please let me know how I can assist with this effort. I'm eager to get started and contribute in any way possible.

Thank you for considering my offer, and thank you once again for creating reveal.js!

Best regards,
Elvis Mao

**Comment by Edit-Mr** [comment]
I'll be working at [my fork](https://github.com/Edit-Mr/revealjs.com) and use [eleventy-plugin-i18n](https://github.com/adamduncan/eleventy-plugin-i18n). Will PR when finished.

**Comment by Edit-Mr** [comment]
#63 @hakimel

**Comment by hakimel** [comment]
I'm glad. to hear reveal.js has been useful to you! Really appreciate your help translating the documentation @Edit-Mr. I've replied with some feedback in the PR and will close this so we can continue the conversation there and get it merged.
